import type { Metadata } from "next";
import "./globals.css";
import { i18nConfig } from "../../../i18nConfig";
import { languages } from "../i18n/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((locale) => {locale})
}

export default function RootLayout({
  children,
  params: {
    locale
  }
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  console.log(locale);
  
  return (
    <html lang={locale}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
